version: '3'

services:
    db:
        image: mysql:8
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_DATABASE: demo
            MYSQL_USER: test
            MYSQL_PASSWORD: test
        command: --default-authentication-plugin=mysql_native_password